### PR TITLE
implement Hash and Eq for ResolvedNode and ResolvedToken.

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
These simply forward to the impls for SyntaxNode and SyntaxToken respectivly.

### CODE REVIEW

**Comment by domenicquirl** [comment]
Hey, thanks for sending a PR! This seems fine to add, so I'm happy to merge this :)

Just as a heads-up though, it might take a bit until this actually goes in and ends up in a release since I'm currently trying to figure out what to do about https://github.com/Kixiron/lasso/issues/47 :/

**Comment by aDotInTheVoid** [comment]
totally understood. i don’t need it urgently at all, as im currently accessing it via git, and i don’t intend to publish to crates.io

**Comment by domenicquirl** [comment]
Alright, thanks for your patience @aDotInTheVoid! There's a new release of `lasso`, which means that everything runs again 🥳 

It seems like GitHub no longer lets me approve CI if I haven't done so within 30 days (which imo is an odd decision, given that I can still merge the PR _without_ CI) - would you mind rebasing onto `master`? I did a quick dependency and clippy update, so CI should be happy once we get to run it ☺️

**Comment by domenicquirl** [comment]
Also, feel free to add a line in the changelog about this change. If you do, you'll probably need to add an "Unreleased" Section since the changelog only starts with version 0.12. 

You don't have to do this though, we can also land the PR just with the rebase and I'll add something when I merge and prep a release.

**Comment by aDotInTheVoid** [comment]
Pushed a rebased version with a changelog entry.

**Comment by domenicquirl** [comment]
Thanks again for following up, and for making the contribution in the first place. This change has now been released with `cstree` version `0.12.1` 🎉

**Pull request merged**
